name: unit-test
on: [push]
jobs:
  runs-unit-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME:
          MONGO_INITDB_ROOT_PASSWORD:
          MONGO_INITDB_DATABASE: accounts
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test